version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_wallet
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - cb-bridge

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_wallet
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
    depends_on:
      - prometheus
    networks:
      - cb-bridge

volumes:
  grafana-storage:

networks:
  cb-bridge:
    external: true
