spring:
  application:
    name: micropay-wallet

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rabbitmq:
    host: rabbit
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

server:
  port: 8110





