name: Wallet - Java CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and Test with Gradle Wrapper
        run: ./gradlew clean build --no-daemon

      - name: Build & push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dockerforomar/micropay-wallet
          tags: latest, ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-to-gke:
    needs: build-test-and-docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Install GKE auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials micropay-test-cluster \
          --zone us-central1-c \
          --project ${{ secrets.GKE_PROJECT }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/rabbit_secret.yaml
          kubectl apply -f k8s/rabbit_deployment.yaml
          kubectl apply -f k8s/rabbit_service.yaml
          kubectl apply -f k8s/db_config_wallet.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/wallet-service \
          wallet-service=docker.io/dockerforomar/micropay-wallet:${{ github.sha }}
          kubectl rollout status deployment/wallet-service


  




